import { StyleSheet } from 'react-native';
import { scaledFont, verticalScale } from '../../styles/typography';
import { Gray } from '../../styles/AppColors';

export const createStyles = (isDark: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDark ? '#111827' : Gray.gray50,
      padding: 20,
    },
    headerSection: {
      alignItems: 'center',
      marginBottom: 32,
      marginTop: 20,
    },
    iconContainer: {
      marginBottom: 16,
    },
    tryAnotherRequestButton: {
      alignSelf: 'center',
      width: '80%',
      backgroundColor: isDark ? '#059669' : '#28a745',
      marginBottom: 20,
    },
    cardContainer: {
      width: '80%',
      backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
      borderRadius: 16,
      padding: 8,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
      marginBottom: 20,
      alignSelf: 'center',
      justifyContent: 'center',
    },
    creditCardIcon: {
      width: 80,
      height: verticalScale(50),
      backgroundColor: isDark ? '#7C3AED' : '#6B73FF',
      borderRadius: 25,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    creditCardSymbol: {
      fontSize: scaledFont(32),
      color: '#FFFFFF',
    },
    title: {
      fontSize: scaledFont(24),
      fontWeight: 'bold',
      color: isDark ? '#A78BFA' : Gray.gray700,
      marginBottom: 8,
      textAlign: 'center',
      fontFamily: 'Poppins',
    },
    subtitle: {
      fontSize: scaledFont(16),
      color: isDark ? '#D1D5DB' : '#374151',
      textAlign: 'center',
      lineHeight: Math.round(scaledFont(16) * 1.15),
      fontWeight: '600',
      fontFamily: 'Poppins',
    },
    formContainer: {
      borderWidth: 1,
      borderColor: isDark ? '#7C3AED' : '#6B73FF',
      backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
      borderRadius: 16,
      padding: 24,
      shadowColor: Gray.gray400,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      marginBottom: 40,
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: scaledFont(16),
      fontWeight: '500',
      color: isDark ? '#60A5FA' : Gray.gray600,
      fontFamily: 'Poppins',
      marginBottom: 16,
    },
    addressSection: {
      borderWidth: 1,
      borderColor: isDark ? '#34D399' : '#32a852',
      backgroundColor: isDark ? '#064E3B' : '#e8fcea',
      borderRadius: 16,
      padding: 12,
      paddingTop: 8,
      paddingBottom: 0,
      marginBottom: 16,
      elevation: 2,
    },
    nameSection: {
      borderWidth: 1,
      borderColor: isDark ? '#60A5FA' : '#0077C8',
      backgroundColor: isDark ? '#0f3b73' : '#d2e5fc',
      borderRadius: 16,
      padding: 12,
      paddingTop: 8,
      paddingBottom: 0,
      marginBottom: 16,
      elevation: 2,
    },
    formSection: {
      borderWidth: 1,
      borderColor: isDark ? '#8B5CF6' : '#8B5CF6',
      backgroundColor: isDark ? '#374151' : '#f7f0ff',
      borderRadius: 16,
      padding: 12,
      paddingTop: 8,
      paddingBottom: 0,
      marginBottom: 16,
      elevation: 2,
    },
    row: {
      marginBottom: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    halfWidth: {
      width: '48%',
      paddingVertical: 12,
      borderWidth: 1,
      borderColor: isDark ? '#8B5CF6' : '#8B5CF6',
      backgroundColor: isDark ? '#374151' : '#f7f0ff',
      borderRadius: 16,
      paddingTop: 8,
      paddingBottom: 0,
      paddingHorizontal: 12,
      elevation: 2,
    },
    resultContainer: {
      alignSelf: 'center',
      width: '90%',
      backgroundColor: isDark ? '#064E3B' : '#F0FDF4',
      borderRadius: 16,
      padding: 16,
      marginTop: 20,
      borderWidth: 1,
      borderColor: isDark ? '#059669' : '#BBF7D0',
    },
    resultTitle: {
      fontSize: scaledFont(14),
      fontWeight: '600',
      color: isDark ? '#6EE7B7' : '#16A34A',
      marginBottom: 8,
      fontFamily: 'Poppins',
    },
    tokenText: {
      fontSize: scaledFont(12),
      color: isDark ? '#A7F3D0' : '#15803D',
      fontFamily: 'Poppins',
      backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
      padding: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: isDark ? '#059669' : '#D1FAE5',
    },
    errorContainer: {
      alignSelf: 'center',
      width: '90%',
      backgroundColor: isDark ? '#7F1D1D' : '#FEF2F2',
      borderRadius: 16,
      padding: 16,
      marginTop: 20,
      borderWidth: 1,
      borderColor: isDark ? '#DC2626' : '#FECACA',
    },
    errorText: {
      fontSize: scaledFont(14),
      color: isDark ? '#FCA5A5' : '#DC2626',
      textAlign: 'center',
      fontFamily: 'Poppins',
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: isDark ? '#111827' : '#f0f0f0',
    },
    keyboardAvoidingView: {
      flex: 1,
    },
    scrollContentContainer: {
      flexGrow: 1,
      paddingBottom: 20,
    },
  });

export const styles = createStyles(false);
