import { StyleSheet } from 'react-native';
import {
  horizontalScale,
  scaledFont,
  verticalScale,
} from '../../styles/typography';
import { createAppStyles } from '../../styles/AppStyles';
import { Gray } from '../../styles/AppColors';

export const createStyles = (isDark: boolean) => {
  const appStyles = createAppStyles(isDark);

  return StyleSheet.create({
    ...appStyles,
    container: {
      flex: 1,
      backgroundColor: isDark ? '#111827' : Gray.gray50,
      paddingVertical: 20,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: isDark ? '#111827' : '#F5F6FA',
    },
    content: {
      flex: 1,
      paddingHorizontal: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerSection: {
      alignItems: 'center',
      marginBottom: 30,
    },
    creditCardSymbol: {
      fontSize: scaledFont(32),
      color: '#FFFFFF',
    },
    paymentIcon: {
      width: horizontalScale(60),
      height: verticalScale(60),
      backgroundColor: isDark ? '#6366F1' : '#6366F1',
      borderRadius: 30,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 20,
    },
    title: {
      fontSize: scaledFont(24),
      fontWeight: 'bold',
      color: isDark ? '#F9FAFB' : Gray.gray700,
      marginBottom: 8,
      textAlign: 'center',
      fontFamily: 'Poppins',
    },
    subtitle: {
      fontSize: scaledFont(16),
      color: isDark ? '#D1D5DB' : Gray.gray600,
      textAlign: 'center',
      fontWeight: 'bold',
      lineHeight: Math.round(scaledFont(16) * 1.15),
      fontFamily: 'Poppins',
    },
    cardContainer: {
      width: '80%',
      backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
      borderRadius: 16,
      padding: 8,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 4,
      },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 4,
      marginBottom: 20,
    },
    resultContainer: {
      width: '80%',
      backgroundColor: isDark ? '#064E3B' : '#F0FDF4',
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: isDark ? '#059669' : '#BBF7D0',
      justifyContent: 'center',
      alignItems: 'center',
    },
    resultTitle: {
      fontSize: scaledFont(14),
      fontWeight: '600',
      color: isDark ? '#6EE7B7' : '#16A34A',
      marginBottom: 8,
      fontFamily: 'Poppins',
    },
    tokenText: {
      fontSize: scaledFont(12),
      color: isDark ? '#A7F3D0' : '#15803D',
      fontFamily: 'Poppins',
      backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
      padding: 8,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: isDark ? '#059669' : '#D1FAE5',
    },
    errorContainer: {
      width: '80%',
      backgroundColor: isDark ? '#7F1D1D' : '#FEF2F2',
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: isDark ? '#DC2626' : '#FECACA',
    },
    errorText: {
      fontSize: scaledFont(14),
      color: isDark ? '#FCA5A5' : '#DC2626',
      textAlign: 'center',
      fontFamily: 'Poppins',
    },
    resultText: {
      fontSize: scaledFont(14),
      color: isDark ? '#6EE7B7' : '#16A34A',
      fontFamily: 'Poppins',
    },
    errorTitle: {
      fontSize: scaledFont(16),
      fontWeight: 'bold',
      color: isDark ? '#FCA5A5' : '#DC2626',
      marginBottom: 4,
    },
    securityBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? '#064E3B' : '#F0FDF4',
      paddingHorizontal: 10,
      marginHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: isDark ? '#059669' : '#BBF7D0',
      marginBottom: 20,
    },
    securityIcon: {
      fontSize: scaledFont(12),
      marginRight: 6,
    },
    securityText: {
      color: isDark ? '#6EE7B7' : '#16A34A',
      fontSize: scaledFont(12),
      fontWeight: '500',
      textAlign: 'center',
      fontFamily: 'Poppins',
    },
    configContainer: {
      width: '100%',
      backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
      borderRadius: 16,
      borderColor: Gray.gray200,
      padding: 20,
      marginBottom: 20,
      shadowColor: Gray.gray400,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      elevation: 4,
    },
    themeConfigContainer: {
      width: '100%',
      backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
      borderRadius: 16,
      borderColor: Gray.gray200,
      padding: 20,
      marginBottom: 20,
      shadowColor: Gray.gray400,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.4,
      shadowRadius: 4,
      elevation: 4,
    },
    configTitle: {
      fontSize: scaledFont(16),
      fontWeight: '500',
      color: isDark ? '#F9FAFB' : '#4B5563',
      marginBottom: 16,
      fontFamily: 'Poppins',
    },
    toggleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    toggleLabel: {
      flex: 1,
      fontSize: scaledFont(14),
      fontWeight: '500',
      color: isDark ? '#D1D5DB' : '#4B5563',
      fontFamily: 'Poppins',
    },
    toggleSwitch: {
      transform: [{ scaleX: 0.8 }, { scaleY: 0.8 }],
    },
    yearFormatRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 8,
      flexWrap: 'wrap',
    },
    yearFormatLabel: {
      fontSize: scaledFont(14),
      color: isDark ? '#D1D5DB' : '#4B5563',
      fontWeight: '500',
      fontFamily: 'Poppins',
    },
    segmentedControl: {
      flexDirection: 'row',
      backgroundColor: isDark ? '#374151' : '#E5E7EB',
      borderRadius: 8,
      padding: 2,
      flexWrap: 'wrap',
    },
    segmentButton: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 6,
      minWidth: 50,
      alignItems: 'center',
    },
    segmentButtonActive: {
      backgroundColor: isDark ? '#1F2937' : '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    segmentButtonText: {
      fontSize: scaledFont(14),
      fontWeight: '500',
      color: isDark ? '#9CA3AF' : '#4B5563',
      fontFamily: 'Poppins',
    },
    segmentButtonTextActive: {
      color: isDark ? '#F9FAFB' : '#1F2937',
      fontWeight: '500',
      fontFamily: 'Poppins',
    },
    currentThemeRow: {
      marginBottom: 12,
    },
    currentThemeLabel: {
      fontSize: scaledFont(14),
      color: isDark ? '#D1D5DB' : '#4B5563',
      fontFamily: 'Poppins',
      fontWeight: '500',
    },
    currentThemeValue: {
      color: isDark ? '#60A5FA' : '#3B82F6',
      fontWeight: '500',
      fontFamily: 'Poppins',
    },
    customThemeLabel: {
      fontSize: scaledFont(14),
      color: isDark ? '#D1D5DB' : '#4B5563',
      fontWeight: '500',
      marginTop: 8,
      marginBottom: 12,
      fontFamily: 'Poppins',
    },
    themeButtonsContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 16,
    },
    themeButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
      borderWidth: 2,
      borderColor: 'transparent',
      minWidth: 100,
      alignItems: 'center',
    },
    blueThemeButton: {
      backgroundColor: isDark ? '#1E3A8A' : '#DBEAFE',
    },
    greenThemeButton: {
      backgroundColor: isDark ? '#064E3B' : '#D1FAE5',
    },
    purpleThemeButton: {
      backgroundColor: isDark ? '#581C87' : '#EDE9FE',
    },
    themeButtonActive: {
      borderColor: isDark ? '#60A5FA' : '#3B82F6',
      shadowColor: isDark ? '#60A5FA' : '#3B82F6',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    themeButtonText: {
      fontSize: scaledFont(14),
      fontWeight: '500',
      color: isDark ? '#F9FAFB' : '#374151',
      fontFamily: 'Poppins',
    },
  });
};

export const styles = createStyles(false);
